services:
  - type: web
    name: weel-backend
    runtime: docker
    repo: https://github.com/setdarovDEV/weel-backend
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SYNC_DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: MINIO_ENDPOINT
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"